name: Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB: ${{ secrets.MONGODB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      USERS: ${{ secrets.USERS }}
      ADMIN: ${{ secrets.ADMIN }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test -- --coverage --ci

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage/lcov-report

  coverage:
    runs-on: ubuntu-latest

    needs: test

    env:
      MONGODB: ${{ secrets.MONGODB }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      USERS: ${{ secrets.USERS }}
      ADMIN: ${{ secrets.ADMIN }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: coverage

      - name: Install dependencies
        run: npm install

      - name: Install coveralls
        run: npm install coveralls --save-dev

      - name: Send coverage data to Coveralls
        run: npx coveralls < coverage/lcov.info

